@extends('layouts.admin')
@section('title','Programs')
@section('page_title','Programs')
@section('content')
<section class="admin-card" data-ajax-crud data-refresh-target="#admin-list-results"><div class="admin-card-head"><div><h2>Programs</h2><p class="text-muted-custom small mb-0 mt-1">Each program keeps its own income, expenses and balance.</p></div><button class="btn btn-accent btn-sm" data-crud-open data-modal="#programModal" data-store-url="{{ route('admin.programs.store') }}"><i class="bi bi-plus-lg me-1"></i>Add Program</button></div>
<div class="admin-list-toolbar"><form class="admin-search financial-filter" method="GET" action="{{ route('admin.programs.index') }}" data-live-search data-live-search-target="#admin-list-results"><div class="search-field"><i class="bi bi-search"></i><input class="form-control" type="search" name="q" value="{{ request('q') }}" placeholder="Search programs..."><button class="search-clear {{ blank(request('q'))?'d-none':'' }}" type="button" data-live-search-clear><i class="bi bi-x-lg"></i></button></div><select class="form-select filter-select" name="status"><option value="">All status</option><option value="active" @selected($status==='active')>Active</option><option value="inactive" @selected($status==='inactive')>Inactive</option></select></form></div>
<div id="admin-list-results"><div class="table-responsive"><table class="table table-hover"><thead><tr><th>Program</th><th>Date</th><th>Income Sources</th><th>Total Income</th><th>Expenses</th><th>Remaining Balance</th><th>Status</th><th class="text-end">Actions</th></tr></thead><tbody>@forelse($programs as $row)<tr><td><strong>{{ $row->name }}</strong><br><small class="text-muted-custom">{{ $row->location ?: 'No location' }}</small></td><td>{{ $row->program_date?->format('M d, Y') ?: '-' }}</td><td>{{ $row->contributors_count }}</td><td class="text-success"><strong>Rs. {{ number_format($row->total_received,2) }}</strong></td><td>Rs. {{ number_format($row->total_expenses,2) }}</td><td><strong>Rs. {{ number_format($row->remaining_balance,2) }}</strong></td><td><span class="status-badge {{ $row->status==='active'?'live':'draft' }}">{{ ucfirst($row->status) }}</span></td><td><div class="action-buttons"><button class="btn-icon" data-crud-edit data-modal="#programModal" data-action="{{ route('admin.programs.update',$row) }}" data-record="{{ json_encode(['name'=>$row->name,'program_date'=>$row->program_date?->format('Y-m-d'),'location'=>$row->location,'description'=>$row->description,'status'=>$row->status,'notes'=>$row->notes]) }}"><i class="bi bi-pencil"></i></button><form method="POST" action="{{ route('admin.programs.destroy',$row) }}" data-ajax-delete data-confirm="Delete this program? Programs with transactions will only be made inactive.">@csrf @method('DELETE')<button class="btn-icon danger"><i class="bi bi-trash3"></i></button></form></div></td></tr>@empty<tr><td colspan="8" class="text-center py-5 text-muted-custom">No programs found.</td></tr>@endforelse</tbody></table></div><div class="admin-pagination">@include('admin.partials.pagination',['paginator'=>$programs])</div></div></section>
<div class="modal fade finance-modal" id="programModal" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content"><form data-ajax-form><input type="hidden" name="_method" value="PUT" data-method disabled><div class="modal-header"><h5 class="modal-title" data-modal-title>Add Program</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3"><div class="col-md-6"><label class="form-label">Program Name</label><input class="form-control" name="name" required><div class="invalid-feedback" data-error-for="name"></div></div><div class="col-md-6"><label class="form-label">Program Date</label><input class="form-control" name="program_date" type="date"></div><div class="col-md-6"><label class="form-label">Location</label><input class="form-control" name="location"></div><div class="col-md-6"><label class="form-label">Status</label><select class="form-select" name="status"><option value="active">Active</option><option value="inactive">Inactive</option></select></div><div class="col-12"><label class="form-label">Description</label><textarea class="form-control" name="description"></textarea></div><div class="col-12"><label class="form-label">Notes</label><textarea class="form-control" name="notes"></textarea></div></div></div><div class="modal-footer"><button class="btn btn-outline-theme" type="button" data-bs-dismiss="modal">Cancel</button><button class="btn btn-accent" type="submit" data-submit><span data-submit-label>Save Program</span></button></div></form></div></div></div>
@endsection
