@extends('layouts.admin')
@section('title','Investment Withdrawals')
@section('page_title','Investment Withdrawals')
@section('content')
<section class="admin-card" data-ajax-crud data-refresh-target="#admin-list-results"><div class="admin-card-head"><div><h2>Investment Withdrawals</h2><p class="text-muted-custom small mb-0 mt-1">Original investment withdrawals are separate from profit payments.</p></div><button class="btn btn-accent btn-sm" data-crud-open data-modal="#withdrawalModal" data-store-url="{{ route('admin.investment-withdrawals.store') }}"><i class="bi bi-plus-lg me-1"></i>Add Withdrawal</button></div>
<div class="admin-list-toolbar"><form class="admin-search financial-filter wide-filter" method="GET" action="{{ route('admin.investment-withdrawals.index') }}" data-live-search data-live-search-target="#admin-list-results"><div class="search-field"><i class="bi bi-search"></i><input class="form-control" type="search" name="q" value="{{ request('q') }}" placeholder="Search withdrawals by reference, method, or investor..."><button class="search-clear {{ blank(request('q'))?'d-none':'' }}" type="button" data-live-search-clear><i class="bi bi-x-lg"></i></button></div><select class="form-select filter-select" name="investor_id"><option value="">All investors</option>@foreach($investors as $i)<option value="{{ $i->id }}" @selected($investorId===$i->id)>{{ $i->name }}</option>@endforeach</select><input type="date" class="form-control filter-date" name="date_from" value="{{ request('date_from') }}" title="Date from"><input type="date" class="form-control filter-date" name="date_to" value="{{ request('date_to') }}" title="Date to"></form><div class="finance-badge">Total Withdrawn: <strong>Rs. {{ number_format($total,2) }}</strong></div></div>
<div id="admin-list-results"><div class="table-responsive"><table class="table table-hover"><thead><tr><th>Date</th><th>Investor</th><th>Method</th><th>Reference</th><th class="text-end">Amount</th></tr></thead><tbody>@forelse($withdrawals as $row)<tr><td>{{ $row->withdrawal_date->format('M d, Y') }}</td><td><strong>{{ $row->investor->name }}</strong></td><td>{{ $row->payment_method ?: '-' }}</td><td>{{ $row->reference_number ?: '-' }}</td><td class="text-end"><strong>Rs. {{ number_format($row->amount,2) }}</strong></td></tr>@empty<tr><td colspan="5" class="text-center py-5 text-muted-custom">No withdrawals yet.</td></tr>@endforelse</tbody></table></div><div class="admin-pagination">@include('admin.partials.pagination',['paginator'=>$withdrawals])</div></div></section>
<div class="modal fade finance-modal" id="withdrawalModal" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><form data-ajax-form><div class="modal-header"><h5 class="modal-title">Add Withdrawal</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3"><div class="col-12"><label class="form-label">Investor</label><select class="form-select" name="investor_id" required><option value="">Select investor</option>@foreach($investors as $i)<option value="{{ $i->id }}">{{ $i->name }} - Current Rs. {{ number_format($i->current_investment,2) }}</option>@endforeach</select></div><div class="col-6"><label class="form-label">Amount</label><input class="form-control" type="number" name="amount" min="0.01" step="0.01" required><div class="invalid-feedback" data-error-for="amount"></div></div><div class="col-6"><label class="form-label">Date</label><input class="form-control" type="date" name="withdrawal_date" value="{{ now()->format('Y-m-d') }}" required></div><div class="col-6"><label class="form-label">Method</label><input class="form-control" name="payment_method"></div><div class="col-6"><label class="form-label">Reference</label><input class="form-control" name="reference_number"></div><div class="col-12"><label class="form-label">Notes</label><textarea class="form-control" name="notes"></textarea></div></div></div><div class="modal-footer"><button class="btn btn-outline-theme" type="button" data-bs-dismiss="modal">Cancel</button><button class="btn btn-accent" type="submit" data-submit data-store-url="{{ route('admin.investment-withdrawals.store') }}">Save Withdrawal</button></div></form></div></div></div>
@endsection
