@extends('layouts.admin')
@section('title','Profit Sharing')
@section('page_title','Profit Sharing')
@section('content')
<div class="row g-4" data-profit-sharing data-preview-url="{{ route('admin.profit-sharing.preview') }}" data-store-url="{{ route('admin.profit-sharing.store') }}">
<div class="col-xl-5"><section class="admin-card"><div class="admin-card-head"><div><h2>Calculate Profit</h2><p class="text-muted-custom small mb-0 mt-1">Investor share is calculated only on net profit.</p></div></div><div class="admin-card-body"><form data-profit-form><div class="row g-3"><div class="col-6"><label class="form-label">From</label><input class="form-control" type="date" name="date_from" required></div><div class="col-6"><label class="form-label">To</label><input class="form-control" type="date" name="date_to" required></div><div class="col-12"><label class="form-label">Total Sales</label><input class="form-control" type="number" step="0.01" min="0" name="total_sales" required></div><div class="col-12"><label class="form-label">Product Cost</label><input class="form-control" type="number" step="0.01" min="0" name="product_cost" required></div><div class="col-12"><label class="form-label">Business Expenses</label><input class="form-control" type="number" step="0.01" min="0" name="business_expenses" required></div><div class="col-12 d-flex gap-2"><button class="btn btn-soft flex-fill" type="button" data-profit-preview>Calculate</button><button class="btn btn-accent flex-fill" type="button" data-profit-confirm disabled>Confirm Profit</button></div><div class="col-12"><div class="small text-danger" data-profit-error></div></div></div></form></div></section></div>
<div class="col-xl-7"><section class="admin-card"><div class="admin-card-head"><h2>Calculation Preview</h2></div><div class="admin-card-body"><div class="row g-3 mb-3"><div class="col-md-4"><div class="finance-summary"><span>Net Profit</span><strong data-net-profit>Rs. 0.00</strong></div></div><div class="col-md-4"><div class="finance-summary"><span>Investors Profit</span><strong data-investor-profit>Rs. 0.00</strong></div></div><div class="col-md-4"><div class="finance-summary"><span>Owner Profit</span><strong data-owner-profit>Rs. 0.00</strong></div></div></div><div class="table-responsive"><table class="table"><thead><tr><th>Investor</th><th>Share</th><th class="text-end">Profit</th></tr></thead><tbody data-profit-allocations><tr><td colspan="3" class="text-center text-muted-custom py-4">Enter figures and click Calculate.</td></tr></tbody></table></div></div></section></div>
</div>
<section class="admin-card mt-4" data-ajax-crud data-refresh-target="#admin-list-results"><div class="admin-card-head"><h2>Confirmed Profit Periods</h2></div><div id="admin-list-results"><div class="table-responsive"><table class="table table-hover"><thead><tr><th>Period</th><th>Sales</th><th>Net Profit</th><th>Investors</th><th>Owner</th><th>Confirmed</th></tr></thead><tbody>@forelse($periods as $row)<tr><td>{{ $row->date_from->format('M d, Y') }} - {{ $row->date_to->format('M d, Y') }}</td><td>Rs. {{ number_format($row->total_sales,2) }}</td><td>Rs. {{ number_format($row->net_profit,2) }}</td><td>Rs. {{ number_format($row->total_investor_profit,2) }}</td><td>Rs. {{ number_format($row->owner_profit,2) }}</td><td>{{ $row->confirmed_at?->format('M d, Y H:i') }}</td></tr>@empty<tr><td colspan="6" class="text-center py-5 text-muted-custom">No confirmed profit periods yet.</td></tr>@endforelse</tbody></table></div><div class="admin-pagination">@include('admin.partials.pagination',['paginator'=>$periods])</div></div></section>
@endsection
